### ISSUE TITLE
Stage 1/4: Loading Datasets

### ISSUE THREAD

**Issue by Carmoruda** [Carmoruda/JetBrains-Academy-Projects#14]
## To-do list
- [ ] Download the dataset from [Kaggle](https://www.kaggle.com/mlg-ulb/creditcardfraud)
- [ ] Import the library
- [ ] Unzip the dataset
- [ ] Read the first 20 rows of the dataset

## Description
**Fraud detection** is what guards your money and property. This process is applied in many industries. Banks, for example, face frauds daily. Perpetrators can try to forge signatures and steal credit cards. There are many ways to counter this, but we will take a look at the role of machine learning. Machine learning is really helpful with fraud detection, as it helps to identify various fraudulent patterns in credit card transactions.

In this stage, we are going to work with a CSV file that contains different credit card transactions and statuses indicating whether the transaction is fraudulent or not.

To access the dataset, we need to use the `read_csv()` method from the [Pandas library](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#pandas.read_csv). The method can accept multiple arguments including the file name, compression type, and so on. The last row of the output is the system message from the Pandas library (see examples). If your program runs without error, no output is expected unless you call the variable name.
## Objectives
To complete this stage, you need to do the following:

1.  Download the dataset from [Kaggle](https://www.kaggle.com/mlg-ulb/creditcardfraud);
2.  Import the library;
3.  Unzip the dataset;
4.  Read the first 20 rows of the dataset.
## Example
*Input: the dataset with information about anonymized credit card transactions, labeled as fraudulent or genuine.*

*Output: the first twenty rows of the dataset in the following format*
```
V1        V2        V3  ...       V27       V28  Amount
0  -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62
1   1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69
2  -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66
3  -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50
4  -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99
5  -0.425966  0.960523  1.141109  ...  0.253844  0.081080    3.67
6   1.229658  0.141004  0.045371  ...  0.034507  0.005168    4.99
7  -0.644269  1.417964  1.074380  ... -1.206921 -1.085339   40.80
8  -0.894286  0.286157 -0.113192  ...  0.011747  0.142404   93.20
9  -0.338262  1.119593  1.044367  ...  0.246219  0.083076    3.68
10  1.449044 -1.176339  0.913860  ...  0.042850  0.016253    7.80
11  0.384978  0.616109 -0.874300  ...  0.042472 -0.054337    9.99
12  1.249999 -1.221637  0.383930  ...  0.026416  0.042422  121.50
13  1.069374  0.287722  0.828613  ...  0.021491  0.021293   27.50
14 -2.791855 -0.327771  1.641750  ... -0.164778 -0.030154   58.80
15 -0.752417  0.345485  2.057323  ... -0.180998  0.129394   15.99
16  1.103215 -0.040296  1.267332  ...  0.092809  0.037051   12.99
17 -0.436905  0.918966  0.924591  ...  0.079692  0.131024    0.89
18 -5.401258 -5.450148  1.186305  ...  0.392053  0.949594   46.80
19  1.492936 -1.029346  0.454795  ...  0.022298  0.007602    5.00

[20 rows x 29 columns]
```
