### ISSUE TITLE
Stage 3/4: Model Development

### ISSUE THREAD

**Issue by Carmoruda** [Carmoruda/JetBrains-Academy-Projects#16]
## To-do list
- [ ] Import the LogisticRegression() model from the sklearn library. 
- [ ] Train your model.
- [ ] Print the parameters

## Description
Model development is also a crucial part of developing a machine learning algorithm. It can help to arrive at the meaning behind anonymous pools of data. Model performs the analysis to make predictions. We will develop a model to detect fraudulent activities with Sklearn.  

For our binary classification problem, we will train a `LogisticRegression()` model using the `sklearn` library.
## Objectives
To complete this stage, you should:

1.  Import the `LogisticRegression()` model from the `sklearn` library.
2.  Train your model. Use `random_state = 2`. Take a look at the [Sklearn Documentation](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html) to learn more about `LogisticRegression()`.
3.  Print the parameters of the model.
## Example
*Input: `x_train` and `y_train` fitted into the algorithm using Sklearn*

*Output: the algorithm parameters*
```Python
{'C': 1.0, 'class_weight': None, 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1,
'l1_ratio': None, 'max_iter': 100, 'multi_class': 'auto', 'n_jobs': None, 'penalty': 'l1', 'random_state': 2,
'solver': 'lbfgs', 'tol': 0.00001, 'verbose': 0, 'warm_start': False}
```
